version: "3"

services:
  server:
    build: server/
    command: python server.py
    volumes:
      - ./server/:/server

  client:
    build: client/
    command: tail -f /dev/null
    depends_on:
      - server